version: '3.8'

services:
  amharic-tts:
    build: .
    container_name: amharic-tts
    ports:
      - "7860:7860"
    volumes:
      # Mount data directories
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    restart: unless-stopped
    
  # GPU version (uncomment if you have NVIDIA GPU)
  # amharic-tts-gpu:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.gpu
  #   container_name: amharic-tts-gpu
  #   ports:
  #     - "7860:7860"
  #   volumes:
  #     - ./data:/app/data
  #     - ./models:/app/models
  #     - ./logs:/app/logs
  #   environment:
  #     - GRADIO_SERVER_NAME=0.0.0.0
  #     - GRADIO_SERVER_PORT=7860
  #     - CUDA_VISIBLE_DEVICES=0
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   restart: unless-stopped
